### PR TITLE
html: removing debug statement

### PR DESCRIPTION
**Pull request by nemtsov**

### CODE REVIEW

**Comment by mwcz** [comment]
I came here to submit a similar request, but I don't think the author uses github.  This is just a mirror.  You'll have better luck at https://code.google.com/p/web-indent/

**Comment by nemtsov** [comment]
@mwcz thanks for info. Google-code has issues from 2011 (with the last one in 2013); so it looks like the project was abandoned.

**Comment by mwcz** [comment]
It's too bad, really.  That debug statement is the only thing standing in between this project and _perfection_. :)

**Comment by nemtsov** [comment]
Well, feel free to use [my fork](https://github.com/nemtsov/JavaScript-Indent), I suppose :)

**Pull request closed without merging**
